#!/bin/bash
# postBuild : Bash script for getting and building gudhi inside container
# HAZARDOUS : not sure the wget of the gudhi archive will work
uname -a
cat /etc/os-release
pwd
ls -alrt
export GUDHI_VERSION="3.9.0"
echo "GUDHI_VERSION = " ${GUDHI_VERSION}
curl -LO "https://github.com/GUDHI/gudhi-devel/releases/download/tags%2Fgudhi-release-${GUDHI_VERSION}/gudhi.${GUDHI_VERSION}.tar.gz" 
ls -alrt

# TEMPORARY : exit on error, because I dont want the temporary image be built and stored
exit -1
